[application]

# App (Project) Name
name = "gabioinf"

asset_dir = "public"

# [web.wasm_opt]
# # The level wasm-opt should target. z is the smallest. 4 is the fastest.
# level = "0"

[web.app]

# HTML title tag content
title = "gabioinf"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# Javascript code file
script = ["https://cdn.jsdelivr.net/npm/ua-parser-js/dist/ua-parser.min.js"]

[web.resource.dev]

script = []
