[application]

# App (Project) Name
name = "gabioinf"

# [web.wasm_opt]
# # The level wasm-opt should target. z is the smallest. 4 is the fastest.
# level = "0"

[web.app]

# HTML title tag content
title = "gabioinf"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

[web.resource.dev]

script = []
