[application]

# App (Project) Name
name = "gabioinf"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "fullstack"

# `build` & `serve` dist path
out_dir = "dist"

asset_dir = "public"

[web.app]

# HTML title tag content
title = "gabioinf"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = [
  "./public/tailwind.css",
  "./public/main.css",
  "./public/navbar.css",
  "./public/alien_links.css",
]

# Javascript code file
script = []

[web.resource.dev]

script = []
