[application]

# App (Project) Name
name = "gabioinf"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "fullstack"

# `build` & `serve` dist path
out_dir = "dist"

asset_dir = "public"

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "z"

[web.app]

# HTML title tag content
title = "gabioinf"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["/tailwind.css", "/main.css", "/navbar.css", "/alien_links.css"]

# Javascript code file
script = ["https://cdn.jsdelivr.net/npm/ua-parser-js/dist/ua-parser.min.js"]

[web.resource.dev]

script = []
