[tasks.api-run]
workspace = false
env = { RUST_LOG = "info" }
install_crate = "cargo-shuttle"
command = "cargo"
args = ["shuttle", "run"]

[tasks.front-serve]
workspace = false
cwd = "./frontend"
install_crate = "dioxus-cli"
command = "dx"
args = ["serve"]

[tasks.front-build]
workspace = false
script_runner = "@shell"
script = '''
rm -rf dist frontend/dist
mkdir dist
cd frontend
dx build --release
cp -r dist/* ../dist
'''

[tasks.clippy]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.format]
clear = true
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.dioxusf-format]
clear = true
workspace = false
install_crate = "dioxus-cli"
command = "dx"
args = ["fmt"]
