[project]
name = "gabioinf"
revision = "1.0"

[providers]
local = "keyring://"

[profiles.default]
DATABASE_URL = { description = "PostgreSQL connection string", required = true }
GABIOINF_SECRET = { description = "GitHub OAuth client secret", required = true }
SENTRY_DSN = { description = "Sentry error reporting endpoint", required = false }

[profiles.default.defaults]
providers = ["local"]
