#!/usr/bin/env python3
"""Regenerate fixtures/synthetic.sql: fake guests, guestbook entries, comments and reactions.

Only the standard library is used. Signatures are small transparent PNGs with a
white squiggle so the guestbook cards look like real doodles.

    python3 fixtures/generate.py > fixtures/synthetic.sql
"""

import base64
import math
import random
import struct
import zlib

random.seed(7)

GUESTS = [
    ("alice_j", "Alice Johnson"),
    ("bob_s", "Bob Smith"),
    ("charlie_b", "Charlie Brown"),
    ("diana_p", "Diana Prince"),
    ("evan_w", "Evan White"),
    ("fiona_g", "Fiona Green"),
    ("george_b", "George Black"),
    ("hannah_r", "Hannah Red"),
    ("ian_b", "Ian Blue"),
    ("julia_y", "Julia Yellow"),
    ("kai_o", "Kai Orange"),
    ("lena_v", "Lena Violet"),
    ("mo_t", "Mo Teal"),
    ("nadia_c", "Nadia Cyan"),
]

MESSAGES = [
    "Hello, world!",
    "Great website! Say hi to Sesh from me.",
    "Found this through the dioxus-spline crate. Thanks for publishing it.",
    "ok you can collect my data now",
    "Loving the design",
    "The Arecibo footer is a nice touch.",
    "Keep up the good work!",
    "Pressed ? and now I know too much.",
    "Impressive site",
    "Thanks for sharing",
    "Looking forward to more rambles",
    "gg",
    "Signed from a phone, sorry for the doodle.",
    "Awesome content",
]

COMMENTS = [
    # (username, body of the parent comment or None, body)
    ("bob_s", None, "Curious how you handle the neighbour list — cell lists or Verlet lists? Part 2 hopefully?"),
    ("diana_p", None, "The build-time highlighting is a neat trick. Does it handle `TOML` fences too?"),
    ("fiona_g", None, "Tables render nicely on mobile, nice work.\n\n- semantic HTML\n- no JS"),
    ("alice_j", "Curious how you handle", "Cell lists for now, Verlet lists once I stop rewriting the integrator every weekend."),
    ("evan_w", "The build-time highlighting", "Only Rust for now according to the README."),
]

# (username, comment opening words or None for the post, stored emoji name)
REACTIONS = [
    ("alice_j", None, "alien"),
    ("bob_s", None, "alien"),
    ("diana_p", None, "heart"),
    ("fiona_g", None, "fire"),
    ("alice_j", "Curious how you handle", "crab"),
    ("bob_s", "Curious how you handle", "party"),
    ("evan_w", "The build-time highlighting", "eyes"),
]


def png(width: int, height: int, pixels: list[list[int]]) -> bytes:
    """Encode an RGBA image where `pixels[y][x]` is the alpha of a white pixel."""
    raw = bytearray()
    for row in pixels:
        raw.append(0)  # filter type: none
        for alpha in row:
            raw += bytes((255, 255, 255, alpha))

    def chunk(kind: bytes, data: bytes) -> bytes:
        body = kind + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(bytes(raw))) + chunk(b"IEND", b"")


def squiggle(width: int = 220, height: int = 80) -> str:
    """A random hand-drawn-looking stroke, returned as base64 PNG."""
    pixels = [[0] * width for _ in range(height)]
    x, y = 12.0, height / 2
    angle = random.uniform(-0.5, 0.5)
    for _ in range(600):
        angle += random.uniform(-0.6, 0.6)
        x += math.cos(angle) * 1.2 + 0.25
        y += math.sin(angle) * 1.2
        y = min(max(y, 8), height - 8)
        if x >= width - 12:
            break
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                px, py = int(x) + dx, int(y) + dy
                if 0 <= px < width and 0 <= py < height:
                    pixels[py][px] = 255 if dx == 0 and dy == 0 else max(pixels[py][px], 140)
    return base64.b64encode(png(width, height, pixels)).decode()


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    print("-- Generated by fixtures/generate.py; do not edit by hand.")
    print("-- Load into a migrated local database with `just seed`.\n")

    print("INSERT INTO guests (github_id, name, username) VALUES")
    rows = [f"({1000 + i}, {sql_string(name)}, {sql_string(username)})" for i, (username, name) in enumerate(GUESTS, 1)]
    print(",\n".join(rows) + "\nON CONFLICT (github_id) DO NOTHING;\n")

    print("INSERT INTO guestbook (message, signature, author_id, created_at) VALUES")
    rows = []
    for i, ((username, _), message) in enumerate(zip(GUESTS, MESSAGES)):
        signature = "NULL" if i % 5 == 4 else sql_string(squiggle())
        rows.append(
            f"({sql_string(message)}, {signature}, "
            f"(SELECT id FROM guests WHERE username = {sql_string(username)}), "
            f"now() - interval '{(len(GUESTS) - i) * 9} days')"
        )
    print(",\n".join(rows) + "\nON CONFLICT (author_id) DO NOTHING;\n")

    print("-- Comments attach to the showcase post; replies look their parent up by its opening words. Re-running is a no-op.")
    for index, (username, parent, body) in enumerate(COMMENTS):
        parent_sql = "NULL" if parent is None else f"(SELECT id FROM comments WHERE body LIKE {sql_string(parent + '%')} ORDER BY id LIMIT 1)"
        print(
            "INSERT INTO comments (post_slug, author_id, parent_id, body, created_at) SELECT "
            f"'blog-rendering-showcase', (SELECT id FROM guests WHERE username = {sql_string(username)}), "
            f"{parent_sql}, {sql_string(body)}, now() - interval '{len(COMMENTS) - index} hours' "
            f"WHERE NOT EXISTS (SELECT 1 FROM comments WHERE body = {sql_string(body)});"
        )

    print("\n-- Reactions use stable names; the UI supplies the glyphs.")
    for username, comment, emoji in REACTIONS:
        target_kind = "post" if comment is None else "comment"
        comment_id = (
            "NULL"
            if comment is None
            else f"(SELECT id FROM comments WHERE body LIKE {sql_string(comment + '%')} ORDER BY id LIMIT 1)"
        )
        print(
            "INSERT INTO reactions (target_kind, post_slug, comment_id, guest_id, emoji) VALUES ("
            f"{sql_string(target_kind)}, 'blog-rendering-showcase', {comment_id}, "
            f"(SELECT id FROM guests WHERE username = {sql_string(username)}), {sql_string(emoji)}) "
            "ON CONFLICT DO NOTHING;"
        )


if __name__ == "__main__":
    main()
