name: Preview Deployment
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GABIOINF_SECRET: ${{ secrets.GABIOINF_SECRET }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch_name.outputs.current_branch }}
    steps:
      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
  create_branch:
    name: Create Neon Branch
    outputs:
      db_url: ${{ steps.create_branch_encode.outputs.db_url }}
      db_url_with_pooler: ${{ steps.create_branch_encode.outputs.db_url_with_pooler }}
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}
    needs: setup
    if: |
      github.event_name == 'pull_request' && (
      github.event.action == 'synchronize'
      || github.event.action == 'opened'
      || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Neon branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          username: "gabioinf_owner"
          branch_name: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          parent: develop
          database: gabioinf
          api_key: ${{ secrets.NEON_API_KEY }}
      - run: |
          echo "DATABASE_URL=${{ steps.create_branch.outputs.db_url_with_pooler }}" >> "$GITHUB_ENV"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Migrate database
        run: |
          cargo install sqlx-cli --no-default-features --features rustls,postgres
          sqlx migrate run
      - id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          secrets: DATABASE_URL=$DATABASE_URL SENTRY_DSN=$SENTRY_DSN GABIOINF_SECRET=$GABIOINF_SECRET
          name: gabioinf-pr-${{ github.event.number }}

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          message: |
            Fly Preview URL :balloon: : ${{ steps.deploy.outputs.url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ env.NEON_PROJECT_ID }}/branches/${{ steps.create_branch.outputs.branch_id }}
  delete_branch:
    name: Delete Branch
    needs: setup
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
      - name: Delete Fly preview
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          name: gabioinf-pr-${{ github.event.number }}
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v2
        if: ${{ github.event.action == 'closed' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.number }}
