name: Preview Deployment
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches-ignore:
      - "dependabot/**"

env:
  NEON_PROJECT_ID: ${{ vars.NEON_PROJECT_ID }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GABIOINF_SECRET: ${{ secrets.GABIOINF_SECRET }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  DOMAIN_URL: gabioinf-pr-${{ github.event.number }}.fly.dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.setup.outputs.current_branch }}
    steps:
      - name: Get git branch name
        id: setup
        uses: tj-actions/branch-names@v8
  create_branch:
    name: Create Branch
    outputs:
      db_url: ${{ steps.create_branch_encode.outputs.db_url }}
      db_url_with_pooler: ${{ steps.create_branch_encode.outputs.db_url_with_pooler }}
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}
    needs: setup
    if: |
      github.event_name == 'pull_request' && (
      github.event.action == 'synchronize'
      || github.event.action == 'opened'
      || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Neon branch
        id: create_branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          username: "gabioinf_owner"
          branch_name: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          parent: main
          database: gabioinf
          api_key: ${{ secrets.NEON_API_KEY }}
      - run: |
          echo "DATABASE_URL=${{ steps.create_branch.outputs.db_url_with_pooler }}" >> "$GITHUB_ENV"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Migrate database
        run: |
          cargo install sqlx-cli --no-default-features --features rustls,postgres
          sqlx migrate run
      - id: deploy
        uses: LilDojd/fly-pr-review-apps@1.2.1
        with:
          secrets: >
            DATABASE_URL=${{ steps.create_branch.outputs.db_url_with_pooler }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            GABIOINF_SECRET=${{ secrets.GABIOINF_SECRET }}
            DOMAIN_URL=gabioinf-pr-${{ github.event.number }}.fly.dev
          name: gabioinf-pr-${{ github.event.number }}

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          message: |
            Fly Preview URL :balloon: : ${{ steps.deploy.outputs.url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ env.NEON_PROJECT_ID }}/branches/${{ steps.create_branch.outputs.branch_id }}
  delete_branch:
    name: Delete Branch
    needs: setup
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}
      - name: Delete Fly preview
        uses: LilDojd/fly-pr-review-apps@1.2.1
        with:
          name: gabioinf-pr-${{ github.event.number }}
      # Points to a recent commit instead of `main` to avoid supply chain attacks. (The latest tag is very old.)
      - name: 🎟 Get GitHub App token
        uses: navikt/github-app-token-generator@b96ff604b2300989cd1105e3fad09199fca56681
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: 🗑 Delete deployment environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          # Use a JWT created with your GitHub App's private key
          token: ${{ steps.get-token.outputs.token }}
          environment: pr-${{ github.event.number }}
          ref: ${{ github.ref_name }}
