name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build server and nextest"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && 
       github.event.workflow_run.conclusion == 'success' && 
       github.event.workflow_run.head_branch == 'main')
    concurrency:
      group: deploy-to-fly
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
